In [1]:
import os


def print_folder_structure(startpath):
    for root, dirs, files in os.walk(startpath):
        # Filter out hidden directories and files
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        files = [f for f in files if not f.startswith(".")]

        level = root.replace(startpath, "").count(os.sep)
        indent = " " * 4 * level
        print(f"{indent}{os.path.basename(root)}/")
        subindent = " " * 4 * (level + 1)
        for file in files:
            print(f"{subindent}{file}")

In [2]:
startpath = r"C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\runs\single_runs\GTSEP_v1-No name-Feb17_Mon_h12"
print_folder_structure(startpath)

GTSEP_v1-No name-Feb17_Mon_h12/
    decision_variables/
        battery_build.csv
        battery_charging.csv
        battery_discharging.csv
        battery_soc.csv
        branch_build.csv
        branch_capacity.csv
        curtailment.csv
        generation.csv
        generator_build.csv
        generator_capacity.csv
        load_shedding.csv
        power_flow.csv
    model_info/
        config.yaml
        model.mps
        model_info.csv
        solution.sol
    results/
        figures/
            bar_effective_capacity_generators.png
            bar_monthly_production.png
            grid_congestion_network_congestion.png
            grid_congestion_network_utilization.png
            grid_simple.png
            grid_sized_generators_and_lines.png
            batteries/
                10_plot_battery_average_hourly_soc_month_.png
                11_plot_battery_average_hourly_soc_month_.png
                12_plot_battery_average_hourly_soc_month_.png
                1_plot_battery_average_hourly_soc_month_.png
                2_plot_battery_average_hourly_soc_month_.png
                3_plot_battery_average_hourly_soc_month_.png
                4_plot_battery_average_hourly_soc_month_.png
                5_plot_battery_average_hourly_soc_month_.png
                6_plot_battery_average_hourly_soc_month_.png
                7_plot_battery_average_hourly_soc_month_.png
                8_plot_battery_average_hourly_soc_month_.png
                9_plot_battery_average_hourly_soc_month_.png
                cake_battery_usage_per_battery_per_month.png
                Murcia_plot_battery_average_hourly_soc_by_month_.png
                plot_battery_average_hourly_soc_per_battery.png
                plot_num_cycles_per_month.png
                Porto_plot_battery_average_hourly_soc_by_month_.png
        tables/
            table_branches_overview.csv
            table_cost_breakdown.csv
            table_generators_overview.csv
            table_generators_production_breakdown.csv
            table_macro_results.csv

In [2]:
# Get the current working directory
current_folder = os.getcwd()

# Call the function to print the folder structure
print_folder_structure(current_folder)

master_project/
    readme.md
    testing.ipynb
    __init__.py
    configs/
        base_config.yaml
        models/
            base_config.yaml
            config_small.yaml
            config_small_2.yaml
            config_test.yaml
        preprocessing/
            base_config.yaml
            config_all.yaml
            config_Iberia.yaml
            config_small.yaml
            battery/
                base_config.yaml
    data/
        countries/
            ne_110m_admin_0_countries.cpg
            ne_110m_admin_0_countries.dbf
            ne_110m_admin_0_countries.prj
            ne_110m_admin_0_countries.README.html
            ne_110m_admin_0_countries.shp
            ne_110m_admin_0_countries.shx
            ne_110m_admin_0_countries.VERSION.txt
        processed/
            elec_s_128_ES_PT/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
                analyzed_data/
                    bar_effective_capacity_generators.png
                    bar_generators_installed_capacity.png
                    grid_battery_cases.png
                    grid_lines_with_sizes.png
                    grid_simple.png
                    grid_sized_generators.png
                    grid_sized_generators_and_lines.png
                    grid_with_ids.png
                    grid_with_line_sizes_and_extensions.png
                    table_branches_overview.csv
                    table_generators_costs_and_emissions.csv
                    table_generators_overview.csv
                    capacity_factors/
                        average_hourly_capacity_factors_with_std.png
                        average_monthly_capacity_factors_with_std.png
                        average_weekly_capacity_factors.png
                        correlation_matrix_offwind-ac.png
                        correlation_matrix_onwind.png
                        correlation_matrix_ror.png
                        correlation_matrix_solar.png
                        offwind-ac_average_hourly_capacity_factors_with_std.png
                        offwind-ac_average_monthly_capacity_factors_with_std.png
                        offwind-ac_heatmap_capacity_factors.png
                        offwind-ac_time_series_capacity_factors.png
                        onwind_average_hourly_capacity_factors_with_std.png
                        onwind_average_monthly_capacity_factors_with_std.png
                        onwind_heatmap_capacity_factors.png
                        onwind_time_series_capacity_factors.png
                        ror_average_hourly_capacity_factors_with_std.png
                        ror_average_monthly_capacity_factors_with_std.png
                        ror_heatmap_capacity_factors.png
                        ror_time_series_capacity_factors.png
                        solar_average_hourly_capacity_factors_with_std.png
                        solar_average_monthly_capacity_factors_with_std.png
                        solar_heatmap_capacity_factors.png
                        solar_time_series_capacity_factors.png
                        time_series_capacity_factors.png
                    demand/
                        grid_demand_daily.png
                        grid_demand_network_hourly.png
                        plot_aggregated_average_hourly_demand_with_stds.png
                        plot_average_hourly_demand_each_month_aggregated.png
                        plot_average_hourly_demand_each_month_ES1 1.png
                        plot_average_hourly_demand_each_season_aggregated.png
                        plot_normalized_demand_hourly_country.png
            elec_s_37_ES_PT/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
                analyzed_data/
                    bar_effective_capacity_generators.png
                    bar_generators_installed_capacity.png
                    grid_battery_cases.png
                    grid_lines_with_sizes.png
                    grid_simple.png
                    grid_sized_generators.png
                    grid_sized_generators_and_lines.png
                    grid_with_ids.png
                    grid_with_line_sizes_and_extensions.png
                    table_branches_overview.csv
                    table_generators_costs_and_emissions.csv
                    table_generators_overview.csv
                    table_genertable_generators_costs_and_emissionsators_methodology.csv
                    capacity_factors/
                        average_hourly_capacity_factors_with_std.png
                        average_monthly_capacity_factors_with_std.png
                        average_weekly_capacity_factors.png
                        correlation_matrix_offwind-ac.png
                        correlation_matrix_onwind.png
                        correlation_matrix_ror.png
                        correlation_matrix_solar.png
                        offwind-ac_average_hourly_capacity_factors_with_std.png
                        offwind-ac_average_monthly_capacity_factors_with_std.png
                        offwind-ac_heatmap_capacity_factors.png
                        offwind-ac_time_series_capacity_factors.png
                        onwind_average_hourly_capacity_factors_with_std.png
                        onwind_average_monthly_capacity_factors_with_std.png
                        onwind_heatmap_capacity_factors.png
                        onwind_time_series_capacity_factors.png
                        ror_average_hourly_capacity_factors_with_std.png
                        ror_average_monthly_capacity_factors_with_std.png
                        ror_heatmap_capacity_factors.png
                        ror_time_series_capacity_factors.png
                        solar_average_hourly_capacity_factors_with_std.png
                        solar_average_monthly_capacity_factors_with_std.png
                        solar_heatmap_capacity_factors.png
                        solar_time_series_capacity_factors.png
                        time_series_capacity_factors.png
                    demand/
                        grid_demand_daily.png
                        grid_demand_network_hourly.png
                        plot_aggregated_average_hourly_demand_with_stds.png
                        plot_average_hourly_demand_each_month_aggregated.png
                        plot_average_hourly_demand_each_month_ES1 0.png
                        plot_average_hourly_demand_each_season_aggregated.png
                        plot_normalized_demand_hourly_country.png
        raw/
            networks/
                base.nc
                elec.nc
                elec_s.nc
                elec_s_1024.nc
                elec_s_1024_ec.nc
                elec_s_128.nc
                elec_s_128_ec.nc
                elec_s_128_ec_lcopt_Co2L-3H.nc
                elec_s_256.nc
                elec_s_256_ec.nc
                elec_s_256_ec_lcopt_Co2L-3H.nc
                elec_s_37.nc
                elec_s_37_ec.nc
                elec_s_37_ec_lcopt_Co2L-3H.nc
                elec_s_512.nc
                elec_s_512_ec.nc
            resources/
                busmap_elec_s.csv
                busmap_elec_s_1024.csv
                busmap_elec_s_128.csv
                busmap_elec_s_256.csv
                busmap_elec_s_37.csv
                busmap_elec_s_512.csv
                connection_costs_s.csv
                costs.csv
                country_shapes.geojson
                europe_shape.geojson
                linemap_elec_s_1024.csv
                linemap_elec_s_128.csv
                linemap_elec_s_256.csv
                linemap_elec_s_37.csv
                linemap_elec_s_512.csv
                load.csv
                natura.tiff
                nuts3_shapes.geojson
                offshore_shapes.geojson
                powerplants.csv
                profile_hydro.nc
                profile_offwind-ac.nc
                profile_offwind-dc.nc
                profile_onwind.nc
                profile_solar.nc
                regions_offshore.geojson
                regions_offshore_elec_s.geojson
                regions_offshore_elec_s_1024.geojson
                regions_offshore_elec_s_128.geojson
                regions_offshore_elec_s_256.geojson
                regions_offshore_elec_s_37.geojson
                regions_offshore_elec_s_512.geojson
                regions_onshore.geojson
                regions_onshore_elec_s.geojson
                regions_onshore_elec_s_1024.geojson
                regions_onshore_elec_s_128.geojson
                regions_onshore_elec_s_256.geojson
                regions_onshore_elec_s_37.geojson
                regions_onshore_elec_s_512.geojson
                shipdensity_raster.nc
    figures/
    master_project/
        LICENSE
        README.md
    notebooks/
        analyze_input_data.ipynb
        analyze_results.ipynb
        run_development.ipynb
    results/
    runs/
        batch_runs/
            1_GTSEP_v0-test small-Feb13_Thu_h09/
                decision_variables/
                    battery_build.csv
                    battery_charging.csv
                    battery_discharging.csv
                    battery_soc.csv
                    branch_build.csv
                    branch_capacity.csv
                    curtailment.csv
                    generation.csv
                    generator_build.csv
                    generator_capacity.csv
                    load_shedding.csv
                    power_flow.csv
                model_info/
                    config.yaml
                    model.mps
                    model_info.csv
                    solution.sol
                results/
                    figures/
                        bar_effective_capacity_generators.png
                        bar_monthly_production.png
                        grid_congestion_network_congestion.png
                        grid_congestion_network_utilization.png
                        grid_simple.png
                        batteries/
                            10_plot_battery_average_hourly_soc_month_.png
                            11_plot_battery_average_hourly_soc_month_.png
                            12_plot_battery_average_hourly_soc_month_.png
                            1_plot_battery_average_hourly_soc_month_.png
                            2_plot_battery_average_hourly_soc_month_.png
                            3_plot_battery_average_hourly_soc_month_.png
                            4_plot_battery_average_hourly_soc_month_.png
                            5_plot_battery_average_hourly_soc_month_.png
                            6_plot_battery_average_hourly_soc_month_.png
                            7_plot_battery_average_hourly_soc_month_.png
                            8_plot_battery_average_hourly_soc_month_.png
                            9_plot_battery_average_hourly_soc_month_.png
                            cake_battery_usage_per_battery_per_month.png
                            Murcia_plot_battery_average_hourly_soc_by_month_.png
                            plot_battery_average_hourly_soc_per_battery.png
                            plot_num_cycles_per_month.png
                            Porto_plot_battery_average_hourly_soc_by_month_.png
                    tables/
                        table_branches_overview.csv
                        table_cost_breakdown.csv
                        table_generators_overview.csv
                        table_generators_production_breakdown.csv
            2_GTSEP_v0-test small 2-Feb13_Thu_h09/
                decision_variables/
                    battery_build.csv
                    battery_charging.csv
                    battery_discharging.csv
                    battery_soc.csv
                    branch_build.csv
                    branch_capacity.csv
                    curtailment.csv
                    generation.csv
                    generator_build.csv
                    generator_capacity.csv
                    load_shedding.csv
                    power_flow.csv
                model_info/
                    config.yaml
                    model.mps
                    model_info.csv
                    solution.sol
                results/
                    figures/
                        bar_effective_capacity_generators.png
                        bar_monthly_production.png
                        grid_congestion_network_congestion.png
                        grid_congestion_network_utilization.png
                        grid_simple.png
                        batteries/
                            10_plot_battery_average_hourly_soc_month_.png
                            11_plot_battery_average_hourly_soc_month_.png
                            12_plot_battery_average_hourly_soc_month_.png
                            1_plot_battery_average_hourly_soc_month_.png
                            2_plot_battery_average_hourly_soc_month_.png
                            3_plot_battery_average_hourly_soc_month_.png
                            4_plot_battery_average_hourly_soc_month_.png
                            5_plot_battery_average_hourly_soc_month_.png
                            6_plot_battery_average_hourly_soc_month_.png
                            7_plot_battery_average_hourly_soc_month_.png
                            8_plot_battery_average_hourly_soc_month_.png
                            9_plot_battery_average_hourly_soc_month_.png
                            cake_battery_usage_per_battery_per_month.png
                            Murcia_plot_battery_average_hourly_soc_by_month_.png
                            plot_battery_average_hourly_soc_per_battery.png
                            plot_num_cycles_per_month.png
                            Porto_plot_battery_average_hourly_soc_by_month_.png
                    tables/
                        table_branches_overview.csv
                        table_cost_breakdown.csv
                        table_generators_overview.csv
                        table_generators_production_breakdown.csv
        single_runs/
            GTSEP_v0-test small 2-Feb13_Thu_h09/
                decision_variables/
                    battery_build.csv
                    battery_charging.csv
                    battery_discharging.csv
                    battery_soc.csv
                    branch_build.csv
                    branch_capacity.csv
                    curtailment.csv
                    generation.csv
                    generator_build.csv
                    generator_capacity.csv
                    load_shedding.csv
                    power_flow.csv
                model_info/
                    config.yaml
                    model.mps
                    model_info.csv
                    solution.sol
                results/
                    figures/
                        bar_effective_capacity_generators.png
                        bar_monthly_production.png
                        grid_congestion_network_congestion.png
                        grid_congestion_network_utilization.png
                        grid_simple.png
                        batteries/
                            10_plot_battery_average_hourly_soc_month_.png
                            11_plot_battery_average_hourly_soc_month_.png
                            12_plot_battery_average_hourly_soc_month_.png
                            1_plot_battery_average_hourly_soc_month_.png
                            2_plot_battery_average_hourly_soc_month_.png
                            3_plot_battery_average_hourly_soc_month_.png
                            4_plot_battery_average_hourly_soc_month_.png
                            5_plot_battery_average_hourly_soc_month_.png
                            6_plot_battery_average_hourly_soc_month_.png
                            7_plot_battery_average_hourly_soc_month_.png
                            8_plot_battery_average_hourly_soc_month_.png
                            9_plot_battery_average_hourly_soc_month_.png
                            cake_battery_usage_per_battery_per_month.png
                            Murcia_plot_battery_average_hourly_soc_by_month_.png
                            plot_battery_average_hourly_soc_per_battery.png
                            plot_num_cycles_per_month.png
                            Porto_plot_battery_average_hourly_soc_by_month_.png
                    tables/
                        table_branches_overview.csv
                        table_cost_breakdown.csv
                        table_generators_overview.csv
                        table_generators_production_breakdown.csv
            GTSEP_v0-test small-Feb11_Tue_h08/
                decision_variables/
                    battery_build.csv
                    battery_charging.csv
                    battery_discharging.csv
                    battery_soc.csv
                    branch_build.csv
                    branch_capacity.csv
                    curtailment.csv
                    generation.csv
                    generator_build.csv
                    generator_capacity.csv
                    load_shedding.csv
                    power_flow.csv
            GTSEP_v0-test small-Feb11_Tue_h09/
                decision_variables/
                    battery_build.csv
                    battery_charging.csv
                    battery_discharging.csv
                    battery_soc.csv
                    branch_build.csv
                    branch_capacity.csv
                    curtailment.csv
                    generation.csv
                    generator_build.csv
                    generator_capacity.csv
                    load_shedding.csv
                    power_flow.csv
                model_info/
                    config.yaml
                    model.mps
                    model_info.csv
                    solution.sol
                results/
            GTSEP_v0-test small-Feb11_Tue_h10/
                decision_variables/
                    battery_build.csv
                    battery_charging.csv
                    battery_discharging.csv
                    battery_soc.csv
                    branch_build.csv
                    branch_capacity.csv
                    curtailment.csv
                    generation.csv
                    generator_build.csv
                    generator_capacity.csv
                    load_shedding.csv
                    power_flow.csv
                model_info/
                    config.yaml
                    model.mps
                    model_info.csv
                    solution.sol
                results/
                    figures/
                        bar_effective_capacity_generators.png
                        bar_monthly_production.png
                        grid_congestion_network_congestion.png
                        grid_congestion_network_utilization.png
                        grid_simple.png
                        batteries/
                            10plot_battery_average_hourly_soc_month_.png
                            10_plot_battery_average_hourly_soc_month_.png
                            11plot_battery_average_hourly_soc_month_.png
                            11_plot_battery_average_hourly_soc_month_.png
                            12plot_battery_average_hourly_soc_month_.png
                            12_plot_battery_average_hourly_soc_month_.png
                            1plot_battery_average_hourly_soc_month_.png

In [3]:
import os
from typing import Union


def count_png_files(folder_path: str) -> int:
    """
    Counts the number of .png files in a nested directory structure.

    Parameters:
        folder_path (str): The path to the root folder.

    Returns:
        int: The total number of .png files found within the folder and its subdirectories.
    """
    count = 0
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            # Check file extension in a case-insensitive manner
            if file.lower().endswith(".png"):
                count += 1
    return count

In [4]:
path = "C:\\Users\\tinus\\OneDrive\\Dokumenter\\0 Master\\code\\master_project\\data\\processed\\elec_s_128_ES_PT\\analyzed_data"

count_png_files(path)

40

In [21]:
import os
import pandas as pd

path = r"C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\data\processed\elec_s_128_ES_PT_no_bat_limit\hourly_demand.csv"
df = pd.read_csv(path, index_col=0)
df.index = pd.to_datetime(df.index)
df.index = range(len(df))
df.index.name = "hour"
df

,ES1 0,ES1 1,ES1 2,ES1 3,ES1 4,ES1 5,ES1 6,ES1 7,ES1 8,PT1 0,PT1 1
hour,,,,,,,,,,,
0,1540.497187,3541.798151,1849.109695,2953.965919,2331.873044,3518.575677,2092.739520,1871.996365,2787.386472,2275.245735,2474.754265
1,1433.747317,3296.366678,1720.974297,2749.268707,2170.284209,3274.753423,1947.721616,1742.275019,2594.232504,2182.798908,2374.201092
2,1335.043919,3069.435065,1602.497346,2560.000934,2020.875437,3049.309730,1813.634710,1622.331663,2415.637880,2041.494173,2220.505827
3,1273.019026,2926.831980,1528.046816,2441.065682,1926.987452,2907.641648,1729.374936,1546.959650,2303.409601,1916.954406,2085.045594
4,1250.287740,2874.569876,1500.761703,2397.477519,1892.578775,2855.722211,1698.494867,1519.336825,2262.279453,1845.104541,2006.895459
...,...,...,...,...,...,...,...,...,...,...,...
8755,2047.626125,4707.751813,2457.833322,3926.406254,3099.521508,4676.884541,2781.665653,2488.254244,3704.989148,3105.830178,3378.169822
8756,1925.453849,4426.862275,2311.185901,3692.135952,2914.587553,4397.836710,2615.696670,2339.791748,3483.929770,2811.245730,3057.754270
8757,1773.509624,4077.523257,2128.802225,3400.776730,2684.587365,4050.788199,2409.282996,2155.150686,3209.000818,2655.092023,2887.907977
8758,1697.939835,3903.778741,2038.093309,3255.868591,2570.196274,3878.182872,2306.622709,2063.319055,3072.264309,2582.284159,2808.715841
8759,1622.973531,3731.421714,1948.108777,3112.117659,2456.718688,3706.955937,2204.782246,1972.220772,2936.619751,2461.576385,2677.423615

In [26]:
df["year"] = 2025
df.index = pd.MultiIndex.from_product([[2025], range(len(df))], names=["year", "hour"])
df.drop(columns="year", inplace=True)
df

                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2025 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775
...                ...          ...          ...          ...          ...
     8755  2047.626125  4707.751813  2457.833322  3926.406254  3099.521508
     8756  1925.453849  4426.862275  2311.185901  3692.135952  2914.587553
     8757  1773.509624  4077.523257  2128.802225  3400.776730  2684.587365
     8758  1697.939835  3903.778741  2038.093309  3255.868591  2570.196274
     8759  1622.973531  3731.421714  1948.108777  3112.117659  2456.718688

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2025 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541
...                ...          ...          ...          ...          ...
     8755  4676.884541  2781.665653  2488.254244  3704.989148  3105.830178
     8756  4397.836710  2615.696670  2339.791748  3483.929770  2811.245730
     8757  4050.788199  2409.282996  2155.150686  3209.000818  2655.092023
     8758  3878.182872  2306.622709  2063.319055  3072.264309  2582.284159
     8759  3706.955937  2204.782246  1972.220772  2936.619751  2461.576385

                 PT1 1
year hour
2025 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
...                ...
     8755  3378.169822
     8756  3057.754270
     8757  2887.907977
     8758  2808.715841
     8759  2677.423615

[8760 rows x 11 columns]

In [27]:
import pandas as pd

# Original dataframe `df` (your existing dataframe)

# Years to replicate
new_years = [2035, 2045]

# Create an empty list to hold the new dataframes
new_dfs = []

# Loop over each new year and create a copy with updated year index
for y in new_years:
    temp_df = df.copy()
    temp_df.index = temp_df.index.set_levels([y], level="year")
    print(temp_df.head())
    new_dfs.append(temp_df)

# Concatenate all dataframes (original + new ones)
df_extended = pd.concat([df] + new_dfs).sort_index()

print(df_extended.head())
print(df_extended.tail())

                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2035 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2035 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541

                 PT1 1
year hour
2035 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2045 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2045 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541

                 PT1 1
year hour
2045 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2025 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2025 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541

                 PT1 1
year hour
2025 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2045 8755  2047.626125  4707.751813  2457.833322  3926.406254  3099.521508
     8756  1925.453849  4426.862275  2311.185901  3692.135952  2914.587553
     8757  1773.509624  4077.523257  2128.802225  3400.776730  2684.587365
     8758  1697.939835  3903.778741  2038.093309  3255.868591  2570.196274
     8759  1622.973531  3731.421714  1948.108777  3112.117659  2456.718688

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2045 8755  4676.884541  2781.665653  2488.254244  3704.989148  3105.830178
     8756  4397.836710  2615.696670  2339.791748  3483.929770  2811.245730
     8757  4050.788199  2409.282996  2155.150686  3209.000818  2655.092023
     8758  3878.182872  2306.622709  2063.319055  3072.264309  2582.284159
     8759  3706.955937  2204.782246  1972.220772  2936.619751  2461.576385

                 PT1 1
year hour
2045 8755  3378.169822
     8756  3057.754270
     8757  2887.907977
     8758  2808.715841
     8759  2677.423615

In [ ]:
utils.load_multi_year_csv_files_from_folder()