In [2]:
import os


def print_folder_structure(startpath):
    for root, dirs, files in os.walk(startpath):
        # Filter out hidden directories and files
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        files = [f for f in files if not f.startswith(".")]

        level = root.replace(startpath, "").count(os.sep)
        indent = " " * 4 * level
        print(f"{indent}{os.path.basename(root)}/")
        subindent = " " * 4 * (level + 1)
        for file in files:
            print(f"{subindent}{file}")

In [3]:
startpath = r"C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\runs\single_runs\May12_Mon_h08-GTSEP_stochastic_v1-37_ES_PT\results"
print_folder_structure(startpath)

results/
    EEV_run/
        model_info_EEV.csv
    EVPI_runs/
        model_info_EVPI_1.csv
        model_info_EVPI_2.csv
        model_info_EVPI_3.csv
        model_info_EVPI_4.csv
        model_info_EVPI_5.csv
        model_info_EVPI_6.csv
    EV_run/
        model_info_EV.csv

In [16]:
VSS = True
EVPI = True
results_folder = startpath
import pandas as pd

In [23]:
ev_path = os.path.join(results_folder, "EV_run", "model_info_EV.csv")
ev_df = pd.read_csv(ev_path)
ev_df

,Objective Value,Optimality Gap (%),Runtime (s),Build Time (s),Optimize Time (s),Total Time (s),Number of Variables,Number of Constraints,Number of Nonzeros,Number of Integer Variables,Number of Binary Variables,Number of Quadratic Constraints,Model Status
0,2.480289e+10,NaN,0.466,5.238622,0.495106,5.733727,29008,34388,91040,0,0,0,2

In [ ]:
rows = []
if VSS or EVPI:
    SP_path = os.path.join(
        os.path.dirname(results_folder), "model_info", "model_info.csv"
    )
    SP_df = pd.read_csv(SP_path)
    SP_df["Label"] = "SP"
    rows.append(SP_df)
if VSS:
    # Read EV
    ev_path = os.path.join(results_folder, "EV_run", "model_info_EV.csv")
    ev_df = pd.read_csv(ev_path)
    ev_df["Label"] = "EV"
    rows.append(ev_df)

    # Read EEV
    eev_path = os.path.join(results_folder, "EEV_run", "model_info_EEV.csv")
    eev_df = pd.read_csv(eev_path)
    eev_df["Label"] = "EEV"
    rows.append(eev_df)

if EVPI:
    # Read all EVPI runs
    evpi_dir = os.path.join(results_folder, "EVPI_runs")
    evpi_files = [
        f
        for f in os.listdir(evpi_dir)
        if f.startswith("model_info_EVPI_") and f.endswith(".csv")
    ]
    evpi_dfs = [pd.read_csv(os.path.join(evpi_dir, f)) for f in evpi_files]
    evpi_all = pd.concat(evpi_dfs, ignore_index=True)

    # Calculate mean and std
    evpi_mean = evpi_all.mean(numeric_only=True)
    evpi_std = evpi_all.std(numeric_only=True)

    evpi_mean["Label"] = "EVPI"
    evpi_std["Label"] = "EVPI std"

    rows.append(evpi_mean.to_frame().T)
    rows.append(evpi_std.to_frame().T)

# Combine all rows
result_df = pd.concat(rows, ignore_index=True)
result_df.set_index("Label", inplace=True)
result_df
save_path = os.path.join(
    os.path.dirname(results_folder), "model_info", "model_info_combined.csv"
)
save_path
result_df.to_csv(save_path)

6 EVPI files found

'C:\\Users\\tinus\\OneDrive\\Dokumenter\\0 Master\\code\\master_project\\runs\\single_runs\\May12_Mon_h08-GTSEP_stochastic_v1-37_ES_PT\\model_info\\model_info_combined.csv'

In [28]:
SP_path = os.path.join(os.path.dirname(results_folder), "model_info", "model_info.csv")
SP_df = pd.read_csv(SP_path)
SP_df["Label"] = "SP"
rows.append(SP_df)
# Combine all rows
result_df = pd.concat(rows, ignore_index=True)
result_df.set_index("Label", inplace=True)
result_df

,Objective Value,Optimality Gap (%),Runtime (s),Build Time (s),Optimize Time (s),Total Time (s),Number of Variables,Number of Constraints,Number of Nonzeros,Number of Integer Variables,Number of Binary Variables,Number of Quadratic Constraints,Model Status
Label,,,,,,,,,,,,,
EV,24802887786.122314,NaN,0.466,5.238622,0.495106,5.733727,29008,34388,91040,0,0,0,2
EEV,25374462208.948261,NaN,0.105,9.624313,0.139748,9.76406,86800,60106,164177,0,0,0,2
EVPI,24846164834.794262,NaN,0.497167,5.621149,0.526865,6.148015,67536.0,34393.333333,96416.0,0.0,0.0,0.0,2.0
EVPI std,993480834.339321,NaN,0.041053,0.430808,0.042415,0.448155,14921.830236,2.065591,2082.115847,0.0,0.0,0.0,0.0
SP,24883023780.207111,NaN,1.371,9.498411,1.394223,10.892634,86800,60106,164177,0,0,0,2

In [4]:
# Get the current working directory
current_folder = os.getcwd()

# Call the function to print the folder structure
print_folder_structure(current_folder)

master_project/
    environment.yml
    gurobi.lic
    play copy.ipynb
    readme.md
    test.csv
    testing.ipynb
    __init__.py
    configs/
        clustering/
            base_config.yaml
            m-1-4-7-10.yaml
            w-3-16-29-42.yaml
        models/
            base_config.yaml
            config_128_sv1_2_weeks.yaml
            config_37_sv1_2_weeks.yaml
            config_37_sv1_2_weeks_EVPI.yaml
            config_37_sv1_2_weeks_EVPI_and_VSS.yaml
            config_37_sv1_2_weeks_no_bats.yaml
            config_37_sv1_2_weeks_VSS.yaml
            config_37_sv1_4_weeks.yaml
            config_37_sv1_4_weeks_EVPI_1.yaml
            config_37_sv1_4_weeks_EVPI_2.yaml
            config_37_sv1_4_weeks_EVPI_3.yaml
            config_37_sv1_4_weeks_EVPI_4.yaml
            config_37_sv1_4_weeks_EVPI_5.yaml
            config_37_sv1_4_weeks_EVPI_6.yaml
            config_37_sv1_4_weeks_mean.yaml
            old/
                config_128_v0.yaml
                config_128_v1.yaml
                config_128_v1a_multi_weeks.yaml
                config_128_v1a_multi_weeks_16.yaml
                config_128_v1a_multi_weeks_2.yaml
                config_128_v1a_multi_weeks_32.yaml
                config_128_v1a_multi_weeks_4.yaml
                config_128_v1a_multi_weeks_8.yaml
                config_128_v1_multi.yaml
                config_128_v2.yaml
                config_37_all.yaml
                config_37_v0.yaml
                config_37_v1.yaml
                config_37_v1a_multi_weeks.yaml
                config_37_v1a_multi_weeks_16.yaml
                config_37_v1a_multi_weeks_2.yaml
                config_37_v1a_multi_weeks_32.yaml
                config_37_v1a_multi_weeks_4.yaml
                config_37_v1a_multi_weeks_8.yaml
                config_37_v1_multi.yaml
                config_37_v1_multi_all.yaml
                config_37_v1_multi_mini.yaml
                config_37_v2.yaml
                config_37_v3.yaml
        preprocessing/
            base_config.yaml
            config_all.yaml
            config_all_128.yaml
            config_all_37.yaml
            config_all_37_no_bat_limit.yaml
            config_Iberia.yaml
            config_Iberia_128_no_bat_limit.yaml
            config_Iberia_37_no_bat.yaml
            config_Iberia_37_no_bat_limit.yaml
            battery/
                base_config.yaml
                config_no_bat_limit.yaml
    data/
        weeks.txt
        countries/
            ne_110m_admin_0_countries.cpg
            ne_110m_admin_0_countries.dbf
            ne_110m_admin_0_countries.prj
            ne_110m_admin_0_countries.README.html
            ne_110m_admin_0_countries.shp
            ne_110m_admin_0_countries.shx
            ne_110m_admin_0_countries.VERSION.txt
        diagrams/
            Stochastic Conceptual Model.drawio (2).png
            Stochastic Conceptual Model.drawio.png
            Stochastic Conceptual Model.drawio.svg
        exploration/
            ENSPRESO_SOLAR_PV_CSP.xlsx
            ENSPRESO_WIND_ONSHORE_OFFSHORE.xlsx
            bundle/
                GDP_per_capita_PPP_1990_2015_v2.nc
                h2_salt_caverns_GWh_per_sqkm.geojson
                je-e-21.03.02.xls
                nama_10r_3popgdp.tsv.gz
                ppp_2019_1km_Aggregated.tif
                corine/
                    clc_colortable_92.lyr
                    CLC_country_coverage_v18_5.pdf
                    clc_legend.xls
                    clc_legend_qgis.txt
                    ETRS_1989_LAEA_L52_M10.prj
                    g250_clc06_V18_5.aux
                    g250_clc06_V18_5.tfw
                    g250_clc06_V18_5.tif
                    g250_clc06_V18_5.tif.aux.xml
                    g250_clc06_V18_5.tif.ovr
                    g250_clc06_V18_5.tif.vat.dbf
                    g250_clc06_V18_5.tif.vat.dbf.xml
                    g250_clc06_V18_5.tif.xml
                    raster metadata.doc
                    readme_V18_5.txt
                    readme_V18_5_clc06.txt
                    readme_V18_5_raster_100m.txt
                    readme_V18_5_raster_250m.txt
                    Legend/
                        clc_legend.avl
                        CLC_legend.clr
                        clc_legend.csv
                        clc_legend.dbf
                        clc_legend.lyr
                        clc_legend.qml
                        clc_legend.sld
                        clc_legend.txt
                        clc_legend.xls
                        clc_legend_qgis.txt
                eea/
                    UNFCCC_v23.csv
                emobility/
                    Bus__count
                    European_countries_car_ownership.csv
                    KFZ__count
                    Lfw__count
                    Lkw__count
                    LoA__count
                    Lzg__count
                    Pkw__count
                    PmA__count
                    Sat__count
                    traffic.tex
                gebco/
                    GEBCO_2014_2D.nc
                natura/
                    natura.tiff
            entsoe/
                Installed_Capacity_ES_2025.csv
                Installed_Capacity_PT_2025.csv
                Total Load Forecast - Year Ahead 2024 pred 2025 ES.csv
                Total Load Forecast - Year Ahead 2024 pred 2025 PT.csv
            TYNDP-2024-Scenarios-Package/
                ENTSOs_TYNDP_2024_Scenarios_Storyline_Report_2023-12-04.pdf
                TYNDP_2024-Scenario-Report-Data-Figures_240522.xlsx
                TYNDP_2024_Scenarios_Methodology_Report_Final_Version_250128.pdf
                TYNDP_2024_Scenarios_Report_Annex_to_the_Final_Version_250128_web.pdf
                TYNDP_2024_Scenarios_Report_FInal_Version_250128_web.pdf
            __MACOSX/
                TYNDP-2024-Scenarios-Package/
        model_descriptions/
            GTSEP stochastic v1.ipynb
            GTSEP v0.ipynb
            GTSEP v1 multi.ipynb
            GTSEP v1.ipynb
            GTSEP v1a multi.ipynb
            GTSEP v2.ipynb
            GTSEP v3.ipynb
        processed/
            elec_s_128_all/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
            elec_s_128_ES_PT/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
                analyzed_data/
                    bar_effective_capacity_generators.png
                    bar_generators_installed_capacity.png
                    grid_battery_cases.png
                    grid_lines_with_sizes.png
                    grid_simple.png
                    grid_sized_generators.png
                    grid_sized_generators_and_lines.png
                    grid_with_ids.png
                    grid_with_line_sizes_and_extensions.png
                    table_branches_overview.csv
                    table_generators_costs_and_emissions.csv
                    table_generators_overview.csv
                    capacity_factors/
                        average_hourly_capacity_factors_with_std.png
                        average_monthly_capacity_factors_with_std.png
                        average_weekly_capacity_factors.png
                        correlation_matrix_offwind-ac.png
                        correlation_matrix_onwind.png
                        correlation_matrix_ror.png
                        correlation_matrix_solar.png
                        offwind-ac_average_hourly_capacity_factors_with_std.png
                        offwind-ac_average_monthly_capacity_factors_with_std.png
                        offwind-ac_heatmap_capacity_factors.png
                        offwind-ac_time_series_capacity_factors.png
                        onwind_average_hourly_capacity_factors_with_std.png
                        onwind_average_monthly_capacity_factors_with_std.png
                        onwind_heatmap_capacity_factors.png
                        onwind_time_series_capacity_factors.png
                        ror_average_hourly_capacity_factors_with_std.png
                        ror_average_monthly_capacity_factors_with_std.png
                        ror_heatmap_capacity_factors.png
                        ror_time_series_capacity_factors.png
                        solar_average_hourly_capacity_factors_with_std.png
                        solar_average_monthly_capacity_factors_with_std.png
                        solar_heatmap_capacity_factors.png
                        solar_time_series_capacity_factors.png
                        time_series_capacity_factors.png
                    demand/
                        grid_demand_daily.png
                        grid_demand_network_hourly.png
                        plot_aggregated_average_hourly_demand_with_stds.png
                        plot_average_hourly_demand_each_month_aggregated.png
                        plot_average_hourly_demand_each_month_ES1 1.png
                        plot_average_hourly_demand_each_season_aggregated.png
                        plot_normalized_demand_hourly_country.png
            elec_s_128_ES_PT_no_bat_limit/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
            elec_s_37_all/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
                analyzed_data/
                    bar_effective_capacity_generators.png
                    bar_generators_installed_capacity.png
                    grid_battery_cases.png
                    grid_lines_with_sizes.png
                    grid_simple.png
                    grid_sized_generators.png
                    grid_sized_generators_and_lines.png
                    grid_with_ids.png
                    grid_with_line_sizes_and_extensions.png
                    table_branches_overview.csv
                    table_generators_overview.csv
                    table_genertable_generators_costs_and_emissionsators_methodology.csv
                    capacity_factors/
                        average_hourly_capacity_factors_with_std.png
                        average_monthly_capacity_factors_with_std.png
                        average_weekly_capacity_factors.png
                        correlation_matrix_offwind-ac.png
                        correlation_matrix_offwind-dc.png
                        correlation_matrix_onwind.png
                        correlation_matrix_ror.png
                        correlation_matrix_solar.png
                        offwind-ac_average_hourly_capacity_factors_with_std.png
                        offwind-ac_average_monthly_capacity_factors_with_std.png
                        offwind-ac_heatmap_capacity_factors.png
                        offwind-ac_time_series_capacity_factors.png
                        onwind_average_hourly_capacity_factors_with_std.png
                        onwind_average_monthly_capacity_factors_with_std.png
                        onwind_heatmap_capacity_factors.png
                        onwind_time_series_capacity_factors.png
                        ror_average_hourly_capacity_factors_with_std.png
                        ror_average_monthly_capacity_factors_with_std.png
                        ror_heatmap_capacity_factors.png
                        ror_time_series_capacity_factors.png
                        solar_average_hourly_capacity_factors_with_std.png
                        solar_average_monthly_capacity_factors_with_std.png
                        solar_heatmap_capacity_factors.png
                        solar_time_series_capacity_factors.png
                        time_series_capacity_factors.png
                    demand/
                        grid_demand_daily.png
                        grid_demand_network_hourly.png
                        plot_aggregated_average_hourly_demand_with_stds.png
                        plot_average_hourly_demand_each_month_aggregated.png
                        plot_average_hourly_demand_each_month_AL1 0.png
                        plot_average_hourly_demand_each_season_aggregated.png
                        plot_normalized_demand_hourly_country.png
            elec_s_37_all_no_bat_limit/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
            elec_s_37_ES_PT/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
                analyzed_data/
                    bar_effective_capacity_generators.png
                    bar_generators_installed_capacity.png
                    grid_battery_cases.png
                    grid_lines_with_sizes.png
                    grid_simple.png
                    grid_sized_generators.png
                    grid_sized_generators_and_lines.png
                    grid_with_ids.png
                    grid_with_line_sizes_and_extensions.png
                    table_branches_overview.csv
                    table_generators_costs_and_emissions.csv
                    table_generators_overview.csv
                    table_genertable_generators_costs_and_emissionsators_methodology.csv
                    capacity_factors/
                        average_hourly_capacity_factors_with_std.png
                        average_monthly_capacity_factors_with_std.png
                        average_weekly_capacity_factors.png
                        correlation_matrix_offwind-ac.png
                        correlation_matrix_onwind.png
                        correlation_matrix_ror.png
                        correlation_matrix_solar.png
                        offwind-ac_average_hourly_capacity_factors_with_std.png
                        offwind-ac_average_monthly_capacity_factors_with_std.png
                        offwind-ac_heatmap_capacity_factors.png
                        offwind-ac_time_series_capacity_factors.png
                        onwind_average_hourly_capacity_factors_with_std.png
                        onwind_average_monthly_capacity_factors_with_std.png
                        onwind_heatmap_capacity_factors.png
                        onwind_time_series_capacity_factors.png
                        ror_average_hourly_capacity_factors_with_std.png
                        ror_average_monthly_capacity_factors_with_std.png
                        ror_heatmap_capacity_factors.png
                        ror_time_series_capacity_factors.png
                        solar_average_hourly_capacity_factors_with_std.png
                        solar_average_monthly_capacity_factors_with_std.png
                        solar_heatmap_capacity_factors.png
                        solar_time_series_capacity_factors.png
                        time_series_capacity_factors.png
                    demand/
                        grid_demand_daily.png
                        grid_demand_network_hourly.png
                        plot_aggregated_average_hourly_demand_with_stds.png
                        plot_average_hourly_demand_each_month_aggregated.png
                        plot_average_hourly_demand_each_month_ES1 0.png
                        plot_average_hourly_demand_each_season_aggregated.png
                        plot_normalized_demand_hourly_country.png
            elec_s_37_ES_PT_no_bat/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
            elec_s_37_ES_PT_no_bat_limit/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
            elec_s_37_ES_PT_no_bat_limit_mini/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
            elec_s_37_ES_PT_no_bat_limit_multi/
                batteries.csv
                branches.csv
                capacity_factors.csv
                config.yaml
                generators.csv
                generator_costs.csv
                hourly_demand.csv
                nodes.csv
        raw/
            networks/
                base.nc
                elec.nc
                elec_s.nc
                elec_s_1024.nc
                elec_s_1024_ec.nc
                elec_s_128.nc
                elec_s_128_ec.nc
                elec_s_128_ec_lcopt_Co2L-3H.nc
                elec_s_256.nc
                elec_s_256_ec.nc
                elec_s_256_ec_lcopt_Co2L-3H.nc
                elec_s_37.nc
                elec_s_37_ec.nc
                elec_s_37_ec_lcopt_Co2L-3H.nc
                elec_s_512.nc
                elec_s_512_ec.nc
            resources/
                busmap_elec_s.csv
                busmap_elec_s_1024.csv
                busmap_elec_s_128.csv
                busmap_elec_s_256.csv
                busmap_elec_s_37.csv
                busmap_elec_s_512.csv
                connection_costs_s.csv
                costs.csv
                country_shapes.geojson
                europe_shape.geojson
                linemap_elec_s_1024.csv
                linemap_elec_s_128.csv
                linemap_elec_s_256.csv
                linemap_elec_s_37.csv
                linemap_elec_s_512.csv
                load.csv
                natura.tiff
                nuts3_shapes.geojson
                offshore_shapes.geojson
                powerplants.csv
                profile_hydro.nc
                profile_offwind-ac.nc
                profile_offwind-dc.nc
                profile_onwind.nc
                profile_solar.nc
                regions_offshore.geojson
                regions_offshore_elec_s.geojson
                regions_offshore_elec_s_1024.geojson
                regions_offshore_elec_s_128.geojson
                regions_offshore_elec_s_256.geojson
                regions_offshore_elec_s_37.geojson
                regions_offshore_elec_s_512.geojson
                regions_onshore.geojson
                regions_onshore_elec_s.geojson
                regions_onshore_elec_s_1024.geojson
                regions_onshore_elec_s_128.geojson
                regions_onshore_elec_s_256.geojson
                regions_onshore_elec_s_37.geojson
                regions_onshore_elec_s_512.geojson
                shipdensity_raster.nc
        scenario_multipliers/
            base_scenarios.csv
            EVPI_1.csv
            EVPI_2.csv
            EVPI_3.csv
            EVPI_4.csv
            EVPI_5.csv
            EVPI_6.csv
            mean.csv
    notebooks/
        analyze_duals.ipynb
        analyze_input_data.ipynb
        analyze_mutli_week_results copy.ipynb

In [5]:
import os
from typing import Union


def count_png_files(folder_path: str) -> int:
    """
    Counts the number of .png files in a nested directory structure.

    Parameters:
        folder_path (str): The path to the root folder.

    Returns:
        int: The total number of .png files found within the folder and its subdirectories.
    """
    count = 0
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            # Check file extension in a case-insensitive manner
            if file.lower().endswith(".png"):
                count += 1
    return count

In [6]:
path = "C:\\Users\\tinus\\OneDrive\\Dokumenter\\0 Master\\code\\master_project\\data\\processed\\elec_s_128_ES_PT\\analyzed_data"

count_png_files(path)

40

In [7]:
import os
import pandas as pd

path = r"C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\data\processed\elec_s_128_ES_PT_no_bat_limit\hourly_demand.csv"
df = pd.read_csv(path, index_col=0)
df.index = pd.to_datetime(df.index)
df.index = range(len(df))
df.index.name = "hour"
df

,ES1 0,ES1 1,ES1 2,ES1 3,ES1 4,ES1 5,ES1 6,ES1 7,ES1 8,PT1 0,PT1 1
hour,,,,,,,,,,,
0,1540.497187,3541.798151,1849.109695,2953.965919,2331.873044,3518.575677,2092.739520,1871.996365,2787.386472,2275.245735,2474.754265
1,1433.747317,3296.366678,1720.974297,2749.268707,2170.284209,3274.753423,1947.721616,1742.275019,2594.232504,2182.798908,2374.201092
2,1335.043919,3069.435065,1602.497346,2560.000934,2020.875437,3049.309730,1813.634710,1622.331663,2415.637880,2041.494173,2220.505827
3,1273.019026,2926.831980,1528.046816,2441.065682,1926.987452,2907.641648,1729.374936,1546.959650,2303.409601,1916.954406,2085.045594
4,1250.287740,2874.569876,1500.761703,2397.477519,1892.578775,2855.722211,1698.494867,1519.336825,2262.279453,1845.104541,2006.895459
...,...,...,...,...,...,...,...,...,...,...,...
8755,2047.626125,4707.751813,2457.833322,3926.406254,3099.521508,4676.884541,2781.665653,2488.254244,3704.989148,3105.830178,3378.169822
8756,1925.453849,4426.862275,2311.185901,3692.135952,2914.587553,4397.836710,2615.696670,2339.791748,3483.929770,2811.245730,3057.754270
8757,1773.509624,4077.523257,2128.802225,3400.776730,2684.587365,4050.788199,2409.282996,2155.150686,3209.000818,2655.092023,2887.907977
8758,1697.939835,3903.778741,2038.093309,3255.868591,2570.196274,3878.182872,2306.622709,2063.319055,3072.264309,2582.284159,2808.715841
8759,1622.973531,3731.421714,1948.108777,3112.117659,2456.718688,3706.955937,2204.782246,1972.220772,2936.619751,2461.576385,2677.423615

In [8]:
df["year"] = 2025
df.index = pd.MultiIndex.from_product([[2025], range(len(df))], names=["year", "hour"])
df.drop(columns="year", inplace=True)
df

                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2025 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775
...                ...          ...          ...          ...          ...
     8755  2047.626125  4707.751813  2457.833322  3926.406254  3099.521508
     8756  1925.453849  4426.862275  2311.185901  3692.135952  2914.587553
     8757  1773.509624  4077.523257  2128.802225  3400.776730  2684.587365
     8758  1697.939835  3903.778741  2038.093309  3255.868591  2570.196274
     8759  1622.973531  3731.421714  1948.108777  3112.117659  2456.718688

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2025 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541
...                ...          ...          ...          ...          ...
     8755  4676.884541  2781.665653  2488.254244  3704.989148  3105.830178
     8756  4397.836710  2615.696670  2339.791748  3483.929770  2811.245730
     8757  4050.788199  2409.282996  2155.150686  3209.000818  2655.092023
     8758  3878.182872  2306.622709  2063.319055  3072.264309  2582.284159
     8759  3706.955937  2204.782246  1972.220772  2936.619751  2461.576385

                 PT1 1
year hour
2025 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
...                ...
     8755  3378.169822
     8756  3057.754270
     8757  2887.907977
     8758  2808.715841
     8759  2677.423615

[8760 rows x 11 columns]

In [9]:
import pandas as pd

# Original dataframe `df` (your existing dataframe)

# Years to replicate
new_years = [2035, 2045]

# Create an empty list to hold the new dataframes
new_dfs = []

# Loop over each new year and create a copy with updated year index
for y in new_years:
    temp_df = df.copy()
    temp_df.index = temp_df.index.set_levels([y], level="year")
    print(temp_df.head())
    new_dfs.append(temp_df)

# Concatenate all dataframes (original + new ones)
df_extended = pd.concat([df] + new_dfs).sort_index()

print(df_extended.head())
print(df_extended.tail())

                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2035 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2035 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541

                 PT1 1
year hour
2035 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2045 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2045 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541

                 PT1 1
year hour
2045 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2025 0     1540.497187  3541.798151  1849.109695  2953.965919  2331.873044
     1     1433.747317  3296.366678  1720.974297  2749.268707  2170.284209
     2     1335.043919  3069.435065  1602.497346  2560.000934  2020.875437
     3     1273.019026  2926.831980  1528.046816  2441.065682  1926.987452
     4     1250.287740  2874.569876  1500.761703  2397.477519  1892.578775

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2025 0     3518.575677  2092.739520  1871.996365  2787.386472  2275.245735
     1     3274.753423  1947.721616  1742.275019  2594.232504  2182.798908
     2     3049.309730  1813.634710  1622.331663  2415.637880  2041.494173
     3     2907.641648  1729.374936  1546.959650  2303.409601  1916.954406
     4     2855.722211  1698.494867  1519.336825  2262.279453  1845.104541

                 PT1 1
year hour
2025 0     2474.754265
     1     2374.201092
     2     2220.505827
     3     2085.045594
     4     2006.895459
                 ES1 0        ES1 1        ES1 2        ES1 3        ES1 4  \
year hour
2045 8755  2047.626125  4707.751813  2457.833322  3926.406254  3099.521508
     8756  1925.453849  4426.862275  2311.185901  3692.135952  2914.587553
     8757  1773.509624  4077.523257  2128.802225  3400.776730  2684.587365
     8758  1697.939835  3903.778741  2038.093309  3255.868591  2570.196274
     8759  1622.973531  3731.421714  1948.108777  3112.117659  2456.718688

                 ES1 5        ES1 6        ES1 7        ES1 8        PT1 0  \
year hour
2045 8755  4676.884541  2781.665653  2488.254244  3704.989148  3105.830178
     8756  4397.836710  2615.696670  2339.791748  3483.929770  2811.245730
     8757  4050.788199  2409.282996  2155.150686  3209.000818  2655.092023
     8758  3878.182872  2306.622709  2063.319055  3072.264309  2582.284159
     8759  3706.955937  2204.782246  1972.220772  2936.619751  2461.576385

                 PT1 1
year hour
2045 8755  3378.169822
     8756  3057.754270
     8757  2887.907977
     8758  2808.715841
     8759  2677.423615

In [10]:
path1 = r"C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\runs\single_runs\May11_Sun_h09-GTSEP_stochastic_v1-37_ES_PT\results"
path2 = r"C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\runs\single_runs\May11_Sun_h10-GTSEP_stochastic_v1-37_ES_PT\results"

In [11]:
import os


def print_all_subfolders_with_file_counts(directory: str):
    """
    Recursively prints all subfolders in the given directory and the number of files in each.

    Args:
        directory (str): Path to the parent directory.
    """
    for root, dirs, files in os.walk(directory):
        relative_path = os.path.relpath(root, directory)
        folder_label = "." if relative_path == "." else relative_path
        print(f"{folder_label}: {len(files)} file(s)")

In [12]:
print_all_subfolders_with_file_counts(path1)

.: 0 file(s)
duals: 1 file(s)
duals\figures: 3 file(s)
duals\figures\dual_interval_histograms: 10 file(s)
duals\tables: 6 file(s)
duals\tables\dual_interval_tables: 10 file(s)
figures: 16 file(s)
figures\generators: 4 file(s)
figures\new_branch_plots: 0 file(s)
tables: 13 file(s)
tables\extended_tables: 3 file(s)

In [13]:
print_all_subfolders_with_file_counts(path2)

.: 0 file(s)
duals: 1 file(s)
duals\figures: 3 file(s)
duals\figures\dual_interval_histograms: 10 file(s)
duals\tables: 6 file(s)
duals\tables\dual_interval_tables: 10 file(s)
figures: 15 file(s)
figures\generators: 4 file(s)
figures\new_branch_plots: 0 file(s)
tables: 14 file(s)
tables\extended_tables: 3 file(s)