In [21]:
# Import python modules
import os
import sys
import pandas as pd
import numpy as np

# Determine the absolute path to the src directory (one level up from notebooks)
module_path = os.path.abspath(os.path.join("..", "src"))
if module_path not in sys.path:
    sys.path.append(module_path)

In [22]:
# Import custom modules
import plotting
import utils

In [23]:
folder = os.path.join(os.path.dirname(os.getcwd()), "configs")

In [24]:
path = os.path.join(folder, "models", "config_37_v1_multi_mini.yaml")
if not utils.load_model_config()["years"]:
    print("Yee")

Path_or_name:
Configuration loaded from c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\base_config.yaml
Yee

In [25]:
data_folder_path = os.path.join(
    os.path.dirname(os.getcwd()), "data", "processed", "elec_s_128_ES_PT_no_bat_limit"
)
data_folder_path

'c:\\Users\\tinus\\OneDrive\\Dokumenter\\0 Master\\code\\master_project\\data\\processed\\elec_s_128_ES_PT_no_bat_limit'

In [26]:
input_data = utils.load_csv_files_from_folder(data_folder_path)

In [27]:
hourly_demand = input_data["hourly_demand"]
hourly_demand

,ES1 0,ES1 1,ES1 2,ES1 3,ES1 4,ES1 5,ES1 6,ES1 7,ES1 8,PT1 0,PT1 1
snapshot,,,,,,,,,,,
2013-01-01 00:00:00,1540.497187,3541.798151,1849.109695,2953.965919,2331.873044,3518.575677,2092.739520,1871.996365,2787.386472,2275.245735,2474.754265
2013-01-01 01:00:00,1433.747317,3296.366678,1720.974297,2749.268707,2170.284209,3274.753423,1947.721616,1742.275019,2594.232504,2182.798908,2374.201092
2013-01-01 02:00:00,1335.043919,3069.435065,1602.497346,2560.000934,2020.875437,3049.309730,1813.634710,1622.331663,2415.637880,2041.494173,2220.505827
2013-01-01 03:00:00,1273.019026,2926.831980,1528.046816,2441.065682,1926.987452,2907.641648,1729.374936,1546.959650,2303.409601,1916.954406,2085.045594
2013-01-01 04:00:00,1250.287740,2874.569876,1500.761703,2397.477519,1892.578775,2855.722211,1698.494867,1519.336825,2262.279453,1845.104541,2006.895459
...,...,...,...,...,...,...,...,...,...,...,...
2013-12-31 19:00:00,2047.626125,4707.751813,2457.833322,3926.406254,3099.521508,4676.884541,2781.665653,2488.254244,3704.989148,3105.830178,3378.169822
2013-12-31 20:00:00,1925.453849,4426.862275,2311.185901,3692.135952,2914.587553,4397.836710,2615.696670,2339.791748,3483.929770,2811.245730,3057.754270
2013-12-31 21:00:00,1773.509624,4077.523257,2128.802225,3400.776730,2684.587365,4050.788199,2409.282996,2155.150686,3209.000818,2655.092023,2887.907977
2013-12-31 22:00:00,1697.939835,3903.778741,2038.093309,3255.868591,2570.196274,3878.182872,2306.622709,2063.319055,3072.264309,2582.284159,2808.715841
2013-12-31 23:00:00,1622.973531,3731.421714,1948.108777,3112.117659,2456.718688,3706.955937,2204.782246,1972.220772,2936.619751,2461.576385,2677.423615

In [28]:
hourly_demand["week"] = hourly_demand.index.isocalendar().week

In [29]:
hourly_demand

,ES1 0,ES1 1,ES1 2,ES1 3,ES1 4,ES1 5,ES1 6,ES1 7,ES1 8,PT1 0,PT1 1,week
snapshot,,,,,,,,,,,,
2013-01-01 00:00:00,1540.497187,3541.798151,1849.109695,2953.965919,2331.873044,3518.575677,2092.739520,1871.996365,2787.386472,2275.245735,2474.754265,1
2013-01-01 01:00:00,1433.747317,3296.366678,1720.974297,2749.268707,2170.284209,3274.753423,1947.721616,1742.275019,2594.232504,2182.798908,2374.201092,1
2013-01-01 02:00:00,1335.043919,3069.435065,1602.497346,2560.000934,2020.875437,3049.309730,1813.634710,1622.331663,2415.637880,2041.494173,2220.505827,1
2013-01-01 03:00:00,1273.019026,2926.831980,1528.046816,2441.065682,1926.987452,2907.641648,1729.374936,1546.959650,2303.409601,1916.954406,2085.045594,1
2013-01-01 04:00:00,1250.287740,2874.569876,1500.761703,2397.477519,1892.578775,2855.722211,1698.494867,1519.336825,2262.279453,1845.104541,2006.895459,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2013-12-31 19:00:00,2047.626125,4707.751813,2457.833322,3926.406254,3099.521508,4676.884541,2781.665653,2488.254244,3704.989148,3105.830178,3378.169822,1
2013-12-31 20:00:00,1925.453849,4426.862275,2311.185901,3692.135952,2914.587553,4397.836710,2615.696670,2339.791748,3483.929770,2811.245730,3057.754270,1
2013-12-31 21:00:00,1773.509624,4077.523257,2128.802225,3400.776730,2684.587365,4050.788199,2409.282996,2155.150686,3209.000818,2655.092023,2887.907977,1
2013-12-31 22:00:00,1697.939835,3903.778741,2038.093309,3255.868591,2570.196274,3878.182872,2306.622709,2063.319055,3072.264309,2582.284159,2808.715841,1
2013-12-31 23:00:00,1622.973531,3731.421714,1948.108777,3112.117659,2456.718688,3706.955937,2204.782246,1972.220772,2936.619751,2461.576385,2677.423615,1

In [30]:
hourly_demand.iloc[-200:].groupby("week").count()

,ES1 0,ES1 1,ES1 2,ES1 3,ES1 4,ES1 5,ES1 6,ES1 7,ES1 8,PT1 0,PT1 1
week,,,,,,,,,,,
1,48,48,48,48,48,48,48,48,48,48,48
52,152,152,152,152,152,152,152,152,152,152,152

In [31]:
num_weeks = [2**i for i in range(6)]
num_weeks

[1, 2, 4, 8, 16, 32]

In [32]:
total_weeks = 52
week_sets = {n: [2 + (total_weeks // n * i) for i in range(n)] for n in num_weeks}

In [33]:
for n, weeks in week_sets.items():
    print(f"Number of weeks: {n}")
    print(weeks)

Number of weeks: 1
[2]
Number of weeks: 2
[2, 28]
Number of weeks: 4
[2, 15, 28, 41]
Number of weeks: 8
[2, 8, 14, 20, 26, 32, 38, 44]
Number of weeks: 16
[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]
Number of weeks: 32
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]

In [34]:
import numpy as np

weeks_dict = {}

for n_weeks in range(1, 52):  # From 1 to 51 representative weeks
    weeks = np.linspace(2, 52, n_weeks, dtype=int)
    weeks = sorted(set(weeks))  # Ensure uniqueness if any duplicates due to rounding
    weeks_dict[len(weeks)] = weeks  # Key is actual number of unique weeks

# Optional: print nicely
for k, v in weeks_dict.items():
    print(f"{k}: {v}")

1: [2]
2: [2, 52]
3: [2, 27, 52]
4: [2, 18, 35, 52]
5: [2, 14, 27, 39, 52]
6: [2, 12, 22, 32, 42, 52]
7: [2, 10, 18, 27, 35, 43, 52]
8: [2, 9, 16, 23, 30, 37, 44, 52]
9: [2, 8, 14, 20, 27, 33, 39, 45, 52]
10: [2, 7, 13, 18, 24, 29, 35, 40, 46, 52]
11: [2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52]
12: [2, 6, 11, 15, 20, 24, 29, 33, 38, 42, 47, 52]
13: [2, 6, 10, 14, 18, 22, 27, 31, 35, 39, 43, 47, 52]
14: [2, 5, 9, 13, 17, 21, 25, 28, 32, 36, 40, 44, 48, 52]
15: [2, 5, 9, 12, 16, 19, 23, 27, 30, 34, 37, 41, 44, 48, 52]
16: [2, 5, 8, 12, 15, 18, 22, 25, 28, 32, 35, 38, 42, 45, 48, 52]
17: [2, 5, 8, 11, 14, 17, 20, 23, 27, 30, 33, 36, 39, 42, 45, 48, 52]
18: [2, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52]
19: [2, 4, 7, 10, 13, 15, 18, 21, 24, 27, 29, 32, 35, 38, 40, 43, 46, 49, 52]
20: [2, 4, 7, 9, 12, 15, 17, 20, 23, 25, 28, 30, 33, 36, 38, 41, 44, 46, 49, 52]
21: [2, 4, 7, 9, 12, 14, 17, 19, 22, 24, 27, 29, 32, 34, 37, 39, 42, 44, 47, 49, 52]
22: [2, 4, 6, 9, 11, 13, 16, 18, 21, 23, 25, 28, 30, 32, 35, 37, 40, 42, 44, 47, 49, 52]
23: [2, 4, 6, 8, 11, 13, 15, 17, 20, 22, 24, 27, 29, 31, 33, 36, 38, 40, 42, 45, 47, 49, 52]
24: [2, 4, 6, 8, 10, 12, 15, 17, 19, 21, 23, 25, 28, 30, 32, 34, 36, 38, 41, 43, 45, 47, 49, 52]
25: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 52]
26: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]
27: [2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]
28: [2, 3, 5, 7, 9, 11, 13, 14, 16, 18, 20, 22, 24, 26, 27, 29, 31, 33, 35, 37, 39, 40, 42, 44, 46, 48, 50, 52]
29: [2, 3, 5, 7, 9, 10, 12, 14, 16, 18, 19, 21, 23, 25, 27, 28, 30, 32, 34, 35, 37, 39, 41, 43, 44, 46, 48, 50, 52]
30: [2, 3, 5, 7, 8, 10, 12, 14, 15, 17, 19, 20, 22, 24, 26, 27, 29, 31, 33, 34, 36, 38, 39, 41, 43, 45, 46, 48, 50, 52]
31: [2, 3, 5, 7, 8, 10, 12, 13, 15, 17, 18, 20, 22, 23, 25, 27, 28, 30, 32, 33, 35, 37, 38, 40, 42, 43, 45, 47, 48, 50, 52]
32: [2, 3, 5, 6, 8, 10, 11, 13, 14, 16, 18, 19, 21, 22, 24, 26, 27, 29, 31, 32, 34, 35, 37, 39, 40, 42, 43, 45, 47, 48, 50, 52]
33: [2, 3, 5, 6, 8, 9, 11, 12, 14, 16, 17, 19, 20, 22, 23, 25, 27, 28, 30, 31, 33, 34, 36, 37, 39, 41, 42, 44, 45, 47, 48, 50, 52]
34: [2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 24, 26, 27, 29, 30, 32, 33, 35, 36, 38, 39, 41, 42, 44, 45, 47, 48, 50, 52]
35: [2, 3, 4, 6, 7, 9, 10, 12, 13, 15, 16, 18, 19, 21, 22, 24, 25, 27, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 43, 44, 46, 47, 49, 50, 52]
36: [2, 3, 4, 6, 7, 9, 10, 12, 13, 14, 16, 17, 19, 20, 22, 23, 24, 26, 27, 29, 30, 32, 33, 34, 36, 37, 39, 40, 42, 43, 44, 46, 47, 49, 50, 52]
37: [2, 3, 4, 6, 7, 8, 10, 11, 13, 14, 15, 17, 18, 20, 21, 22, 24, 25, 27, 28, 29, 31, 32, 33, 35, 36, 38, 39, 40, 42, 43, 45, 46, 47, 49, 50, 52]
38: [2, 3, 4, 6, 7, 8, 10, 11, 12, 14, 15, 16, 18, 19, 20, 22, 23, 24, 26, 27, 29, 30, 31, 33, 34, 35, 37, 38, 39, 41, 42, 43, 45, 46, 47, 49, 50, 52]
39: [2, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15, 16, 17, 19, 20, 21, 23, 24, 25, 27, 28, 29, 30, 32, 33, 34, 36, 37, 38, 40, 41, 42, 44, 45, 46, 48, 49, 50, 52]
40: [2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 28, 30, 31, 32, 34, 35, 36, 37, 39, 40, 41, 43, 44, 45, 46, 48, 49, 50, 52]
41: [2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 25, 27, 28, 29, 30, 32, 33, 34, 35, 37, 38, 39, 40, 42, 43, 44, 45, 47, 48, 49, 50, 52]
42: [2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25, 26, 27, 28, 30, 31, 32, 33, 34, 36, 37, 38, 39, 41, 42, 43, 44, 45, 47, 48, 49, 50, 52]
43: [2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 52]
44: [2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 52]
45: [2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 52]
46: [2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52]
47: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52]
48: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52]
49: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52]
50: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52]
51: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

In [35]:
import numpy as np

# Choose a reasonable subset of week counts
selected_week_counts = [2, 4, 6, 8, 12, 16, 26, 36, 52]

# Generate the dictionary
weeks_subset = {
    n: sorted(set(np.linspace(2, 52, n, dtype=int))) for n in selected_week_counts
}

# Optional: print to inspebct
for k, v in weeks_subset.items():
    print(f"{k}: {v}")

2: [2, 52]
4: [2, 18, 35, 52]
6: [2, 12, 22, 32, 42, 52]
8: [2, 9, 16, 23, 30, 37, 44, 52]
12: [2, 6, 11, 15, 20, 24, 29, 33, 38, 42, 47, 52]
16: [2, 5, 8, 12, 15, 18, 22, 25, 28, 32, 35, 38, 42, 45, 48, 52]
26: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]
36: [2, 3, 4, 6, 7, 9, 10, 12, 13, 14, 16, 17, 19, 20, 22, 23, 24, 26, 27, 29, 30, 32, 33, 34, 36, 37, 39, 40, 42, 43, 44, 46, 47, 49, 50, 52]
52: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

In [36]:
def generate_evenly_spaced_weeks(n_weeks):
    return sorted(
        set(int(round(w)) for w in np.linspace(1, 52, n_weeks + 2)[1:])  # exclude edges
    )


# Reasonable subset of week counts to test with
selected_week_counts = [2, 4, 6, 8, 12, 16, 26, 36, 52]

weeks_subset = {n: generate_evenly_spaced_weeks(n) for n in selected_week_counts}

# Optional: Print the dictionary
for n, weeks in weeks_subset.items():
    print(f"{n}: {weeks}")

2: [18, 35, 52]
4: [11, 21, 32, 42, 52]
6: [8, 16, 23, 30, 37, 45, 52]
8: [7, 12, 18, 24, 29, 35, 41, 46, 52]
12: [5, 9, 13, 17, 21, 25, 28, 32, 36, 40, 44, 48, 52]
16: [4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52]
26: [3, 5, 7, 9, 10, 12, 14, 16, 18, 20, 22, 24, 26, 27, 29, 31, 33, 35, 37, 39, 41, 43, 44, 46, 48, 50, 52]
36: [2, 4, 5, 7, 8, 9, 11, 12, 13, 15, 16, 18, 19, 20, 22, 23, 24, 26, 27, 29, 30, 31, 33, 34, 35, 37, 38, 40, 41, 42, 44, 45, 46, 48, 49, 51, 52]
52: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

In [37]:
weeks = {
    2: [21, 42],
    4: [11, 21, 42, 52],
    8: [5, 11, 16, 21, 32, 37, 42, 52],
    16: [5, 8, 11, 13, 16, 19, 21, 26, 29, 32, 35, 37, 40, 42, 47, 52],
    32: [
        2,
        4,
        5,
        7,
        8,
        10,
        11,
        13,
        14,
        16,
        17,
        19,
        20,
        21,
        23,
        24,
        26,
        28,
        29,
        31,
        32,
        34,
        35,
        37,
        39,
        40,
        42,
        44,
        47,
        49,
        50,
        52,
    ],
}

In [38]:
weeks

{2: [21, 42],
 4: [11, 21, 42, 52],
 8: [5, 11, 16, 21, 32, 37, 42, 52],
 16: [5, 8, 11, 13, 16, 19, 21, 26, 29, 32, 35, 37, 40, 42, 47, 52],
 32: [2,
  4,
  5,
  7,
  8,
  10,
  11,
  13,
  14,
  16,
  17,
  19,
  20,
  21,
  23,
  24,
  26,
  28,
  29,
  31,
  32,
  34,
  35,
  37,
  39,
  40,
  42,
  44,
  47,
  49,
  50,
  52]}

In [39]:
config_name = "37_v1a_multi_weeks"
to_change = {"representative_periods": weeks[8]}
suffix = "_4"
utils.copy_and_modify_config(config_name, to_change, suffix=suffix)

New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_37_v1a_multi_weeks_4.yaml

'c:\\Users\\tinus\\OneDrive\\Dokumenter\\0 Master\\code\\master_project\\configs\\models\\config_37_v1a_multi_weeks_4.yaml'

In [46]:
config_names = ["37_v1a_multi_weeks", "128_v1a_multi_weeks"]
weeks
new_name_dict = {}
for config_name in config_names:
    new_name_list = []
    for num_weeks, ws in weeks.items():
        to_change = {"representative_periods": ws}
        suffix = f"_{num_weeks}"
        utils.copy_and_modify_config(config_name, to_change, suffix=suffix)
        new_name = f"{config_name}{suffix}"
        new_name_list.append(new_name)
    new_name_dict[config_name] = new_name_list

New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_37_v1a_multi_weeks_2.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_37_v1a_multi_weeks_4.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_37_v1a_multi_weeks_8.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_37_v1a_multi_weeks_16.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_37_v1a_multi_weeks_32.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_128_v1a_multi_weeks_2.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_128_v1a_multi_weeks_4.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_128_v1a_multi_weeks_8.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_128_v1a_multi_weeks_16.yaml
New config saved to: c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_128_v1a_multi_weeks_32.yaml

In [47]:
print(new_name_dict)

{'37_v1a_multi_weeks': ['37_v1a_multi_weeks_2', '37_v1a_multi_weeks_4', '37_v1a_multi_weeks_8', '37_v1a_multi_weeks_16', '37_v1a_multi_weeks_32'], '128_v1a_multi_weeks': ['128_v1a_multi_weeks_2', '128_v1a_multi_weeks_4', '128_v1a_multi_weeks_8', '128_v1a_multi_weeks_16', '128_v1a_multi_weeks_32']}